Update estilo button banner.
UX-Alkosto/webcomponents pull request #56
Opened 2021-06-11 20:17 UTC by alejaCrea20

Update estilos button banner.

2021-06-11 20:18 UTC, alejaCrea20 commented
Update estilo button banner.

2021-06-11 20:49 UTC, miguelcolmenares requested changes

2021-06-11 20:49 UTC, miguelcolmenares commented on components/button/css/index.js
> +    font-size: 16px;
creo q no deberías cambiar esto aquí porque estaríamos forzando q siempre sea ese tamaño en donde sea que implementemos el botón, creería q debemos dejarlo con 1rem y definir ese tamaño desde una hoja de estilos Global

2021-06-15 16:44 UTC, miguelcolmenares approved these changes

2021-06-15 16:44 UTC, merged

2021-06-15 16:45 UTC, miguelcolmenares commented on components/button/css/index.js
> +    font-size: 16px;
@alejaCrea20 creé una variable para definir el font size en 16px por defecto este valor se puede definir con la variable css --font-base